[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sereleum"
version = "0.1.0"
description = "Sereleum backend"
requires-python = ">=3.10"

dependencies = [
    "chromadb==1.3.4",
    "smartscan @ git+https://github.com/smartscanapp/smartscan-lib.git@dev",
    "llm_connect @ git+https://github.com/dev-diaries41/llm-connect.git",
    "aiosqlite==0.22.1",
    "matplotlib==3.10.8",
    "openai==2.14.0",
    "scikit-learn==1.7.2",
    "tiktoken==0.12.0",
    "pytest==9.0.2",
    "pytest-asyncio"
]

[project.optional-dependencies]
api = [
    "fastapi==0.121.2",
    "python-multipart==0.0.20",
    "dramatiq[redis]==2.0.0", 
    " sse-starlette==3.2.0"
]

[tool.setuptools]
packages = ["sereleum", "api"]