"""initial

Revision ID: 4fde057f8189
Revises: 
Create Date: 2026-07-04 18:42:23.808390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fde057f8189'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_clusters',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('prototype_size', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('mean_similarity', sa.Float(), nullable=False),
    sa.Column('std_similarity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts_cluster_crossref',
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('cluster_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['prompt_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompts_cluster_crossref')
    op.drop_table('prompts')
    op.drop_table('prompt_clusters')
    # ### end Alembic commands ###
