class Routes:
    BASE_PROMPTS_ENDPOINT = "/api/prompts"
    ADD_PROMPTS_ENDPOINT = f"{BASE_PROMPTS_ENDPOINT}/add"
    ADD_PROMPTS_FILE_ENDPOINT = f"{BASE_PROMPTS_ENDPOINT}/add/file"
    GET_PROMPTS_OVERVIEW_ENDPOINT = f"{BASE_PROMPTS_ENDPOINT}/overview"
    COUNT_PROMPTS_ENDPOINT = f"{BASE_PROMPTS_ENDPOINT}/count"
    QUERY_PROMPTS_ENDPOINT = f"{BASE_PROMPTS_ENDPOINT}/query"
    SSE_PROMPTS_INDEX_PROGRESS = f"sse/prompts/index/progress"

    BASE_CLUSTER_ENDPOINT = "/api/clusters"
    GET_TOP_CLUSTER_ENDPOINT = f"{BASE_CLUSTER_ENDPOINT}/top"
    COUNT_CLUSTERS_ENDPOINT = f"{BASE_CLUSTER_ENDPOINT}/count"
    GET_CLUSTER_LABELS_ENDPOINT = f"{BASE_CLUSTER_ENDPOINT}/labels"
    GET_CLUSTER_ACCURACY_ENDPOINT = f"{BASE_CLUSTER_ENDPOINT}/accuracy"
    GET_CLUSTER_PLOT_ENDPOINT = f"{BASE_CLUSTER_ENDPOINT}/plot"

