class Routes:
    BASE_PROMPTS_ENDPOINT = "/api/prompts"
    GET_PROMPTS_BY_IDS_ENDPOINT = "/api/prompts/ids"
    ADD_PROMPTS_ENDPOINT = f"{BASE_PROMPTS_ENDPOINT}/add"
    ADD_PROMPTS_FILE_ENDPOINT = f"{BASE_PROMPTS_ENDPOINT}/add/file"
    GET_PROMPTS_OVERVIEW_ENDPOINT = f"{BASE_PROMPTS_ENDPOINT}/overview"
    COUNT_PROMPTS_ENDPOINT = f"{BASE_PROMPTS_ENDPOINT}/count"
    QUERY_PROMPTS_ENDPOINT = f"{BASE_PROMPTS_ENDPOINT}/query"
    SSE_PROMPTS_INDEX_PROGRESS = "/sse/prompts/index/progress"

    BASE_CLUSTER_ENDPOINT = "/api/clusters"
    COUNT_CLUSTERS_ENDPOINT = f"{BASE_CLUSTER_ENDPOINT}/count"
    GET_CLUSTER_PLOT_ENDPOINT = f"{BASE_CLUSTER_ENDPOINT}/plot"
    MERGE_CLUSTERS_ENDPOINT = f"{BASE_CLUSTER_ENDPOINT}/merge"
    SSE_PROMPTS_CLUSTER_STATUS = "/sse/prompts/cluster/status"

